# SovSwift PDF Report Generator
# Author: Elvis Mogere

from fpdf import FPDF
import datetime
import sys

class SovSwiftReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(0, 102, 204)
        self.cell(0, 15, "SovSwift Security", ln=True, align="C")
        self.set_font("Helvetica", "", 11)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "Professional Vulnerability Assessment Report", ln=True, align="C")
        self.set_draw_color(0, 102, 204)
        self.set_line_width(0.8)
        self.line(10, 30, 200, 30)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"SovSwift Security | Confidential | Page {self.page_no()}", align="C")

def generate_pdf(target, ip, scan_time, results, open_ports):
    pdf = SovSwiftReport()
    pdf.add_page()

    # Report info
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Reconnaissance Report", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_fill_color(240, 245, 255)
    pdf.cell(0, 8, f"  Target     : {target}", ln=True, fill=True)
    pdf.cell(0, 8, f"  IP Address : {ip}", ln=True, fill=True)
    pdf.cell(0, 8, f"  Scan Time  : {scan_time}", ln=True, fill=True)
    pdf.cell(0, 8, f"  Open Ports : {len(open_ports)}", ln=True, fill=True)
    pdf.ln(5)

    # Port results
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(0, 10, "Port Scan Results", ln=True)
    pdf.set_text_color(0, 0, 0)

    for result in results:
        status = result["status"]
        port = result["port"]
        service = result["service"]
        banner = result.get("banner", "")

        if status == "OPEN":
            pdf.set_fill_color(220, 255, 220)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 8, f"  [OPEN]  Port {port} - {service}", ln=True, fill=True)
            if banner and banner != "Could not grab banner":
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(0, 7, f"         Banner: {banner[:150]}", fill=False)
                pdf.set_text_color(0, 0, 0)
        else:
            pdf.set_fill_color(250, 250, 250)
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(0, 8, f"  [closed] Port {port} - {service}", ln=True, fill=True)

    pdf.ln(5)

    # Risk notes
    if open_ports:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(204, 0, 0)
        pdf.cell(0, 10, "Risk Assessment", ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 10)

        risk_notes = {
            "22": "SSH exposed: verify strong passwords and key-based auth only",
            "80": "HTTP open: unencrypted traffic, check for sensitive data exposure",
            "21": "FTP open: often allows anonymous login, high risk",
            "23": "Telnet open: completely unencrypted protocol, critical risk",
            "3306": "MySQL exposed: database directly accessible, critical risk"
        }

        for p in open_ports:
            port_num = p.split("/")[0]
            if port_num in risk_notes:
                pdf.set_fill_color(255, 240, 240)
                pdf.cell(0, 8, f"  ! {risk_notes[port_num]}", ln=True, fill=True)

    pdf.ln(5)

    # Footer note
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 8, "This report was generated by SovSwift Security Toolkit.", ln=True)
    pdf.cell(0, 8, "For professional security assessments contact: SovSwift Security, Nairobi, Kenya.", ln=True)

    filename = f"sovswift_report_{target}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf.output(filename)
    print(f"PDF report saved to: {filename}")
    return filename
