# SovSwift Security Toolkit
# Script 1 - Recon + Port Scanner + Report Generator
# Author: Elvis Mogere

import socket
import datetime

def run_scan(target):
    report_lines = []
    report_lines.append("=" * 40)
    report_lines.append("    SovSwift Security - Recon Report")
    report_lines.append("=" * 40)

    try:
        ip = socket.gethostbyname(target)
    except socket.gaierror:
        print("Could not resolve target.")
        return

    scan_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_lines.append(f"Target     : {target}")
    report_lines.append(f"IP Address : {ip}")
    report_lines.append(f"Scan Time  : {scan_time}")
    report_lines.append("-" * 40)
    report_lines.append("Port Scan Results:")
    report_lines.append("")

    common_ports = {
        21: "FTP",
        22: "SSH",
        23: "Telnet",
        80: "HTTP",
        443: "HTTPS",
        3306: "MySQL",
        8080: "HTTP-Alt"
    }

    open_ports = []

    for port, service in common_ports.items():
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(1)
        result = sock.connect_ex((ip, port))
        if result == 0:
            status = "[OPEN]"
            open_ports.append(f"{port}/{service}")
        else:
            status = "[closed]"
        line = f"  {status:<10} Port {port} - {service}"
        report_lines.append(line)
        print(line)
        sock.close()

    report_lines.append("")
    report_lines.append("-" * 40)
    report_lines.append(f"Open ports found: {len(open_ports)}")

    if open_ports:
        report_lines.append(f"Open: {', '.join(open_ports)}")
        report_lines.append("")
        report_lines.append("Risk Notes:")
        for p in open_ports:
            if "22" in p:
                report_lines.append("  - SSH open: check for brute force exposure")
            if "80" in p:
                report_lines.append("  - HTTP open: unencrypted web traffic, check for vulnerabilities")
            if "21" in p:
                report_lines.append("  - FTP open: often allows anonymous login, high risk")
            if "23" in p:
                report_lines.append("  - Telnet open: unencrypted protocol, critical risk")
            if "3306" in p:
                report_lines.append("  - MySQL open: database exposed to network, critical risk")

    report_lines.append("=" * 40)
    report_lines.append("Report generated by SovSwift Security Toolkit")
    report_lines.append("=" * 40)

    filename = f"sovswift_report_{target}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    with open(filename, "w") as f:
        f.write("\n".join(report_lines))

    print(f"\nReport saved to: {filename}")

target = input("Enter target domain or IP: ")
print("\n--- SovSwift Recon Report ---")
run_scan(target)# SovSwift Security Toolkit
# Script 1 - Recon + Port Scanner
# Author: Elvis Mogere

import socket
import datetime

target = input("Enter target domain or IP: ")
print("\n--- SovSwift Recon Report ---")
print(f"Target     : {target}")
print(f"Scan Time  : {datetime.datetime.now()}")

try:
    ip = socket.gethostbyname(target)
    print(f"IP Address : {ip}")
except socket.gaierror:
    print("Could not resolve target.")
    exit()

print("\nScanning common ports...")
print("-" * 30)

common_ports = {
    21: "FTP",
    22: "SSH",
    23: "Telnet",
    80: "HTTP",
    443: "HTTPS",
    3306: "MySQL",
    8080: "HTTP-Alt"
}

open_ports = []

for port, service in common_ports.items():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(1)
    result = sock.connect_ex((ip, port))
    if result == 0:
        print(f"  [OPEN]   Port {port} - {service}")
        open_ports.append(port)
    else:
        print(f"  [closed] Port {port} - {service}")
    sock.close()

print("-" * 30)
print(f"Open ports found: {len(open_ports)}")
print("-----------------------------\n")
