# SovSwift Security Toolkit v2.0
# Recon + Port Scanner + Banner Grabbing + Report Generator
# Author: Elvis Mogere

import socket
import datetime

def grab_banner(ip, port):
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(2)
        sock.connect((ip, port))
        sock.send(b"HEAD / HTTP/1.0\r\n\r\n")
        banner = sock.recv(1024).decode(errors="ignore").strip()
        sock.close()
        return banner[:200] if banner else "No banner"
    except:
        return "Could not grab banner"

def run_scan(target):
    report_lines = []
    report_lines.append("=" * 50)
    report_lines.append("      SovSwift Security - Recon Report v2.0")
    report_lines.append("=" * 50)

    try:
        ip = socket.gethostbyname(target)
    except socket.gaierror:
        print("Could not resolve target.")
        return

    scan_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_lines.append(f"Target     : {target}")
    report_lines.append(f"IP Address : {ip}")
    report_lines.append(f"Scan Time  : {scan_time}")
    report_lines.append("-" * 50)
    report_lines.append("Port Scan Results:")
    report_lines.append("")

    common_ports = {
        21: "FTP",
        22: "SSH",
        23: "Telnet",
        80: "HTTP",
        443: "HTTPS",
        3306: "MySQL",
        8080: "HTTP-Alt"
    }

    open_ports = []

    for port, service in common_ports.items():
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(1)
        result = sock.connect_ex((ip, port))
        if result == 0:
            status = "[OPEN]"
            open_ports.append(f"{port}/{service}")
            banner = grab_banner(ip, port)
            line = f"  {status:<10} Port {port} - {service}"
            report_lines.append(line)
            report_lines.append(f"             Banner: {banner}")
            print(line)
            print(f"             Banner: {banner}")
        else:
            status = "[closed]"
            line = f"  {status:<10} Port {port} - {service}"
            report_lines.append(line)
            print(line)
        sock.close()

    report_lines.append("")
    report_lines.append("-" * 50)
    report_lines.append(f"Open ports found: {len(open_ports)}")

    if open_ports:
        report_lines.append(f"Open: {', '.join(open_ports)}")
        report_lines.append("")
        report_lines.append("Risk Notes:")
        for p in open_ports:
            if "22" in p:
                report_lines.append("  - SSH open: check for brute force exposure")
            if "80" in p:
                report_lines.append("  - HTTP open: unencrypted web traffic, check for vulnerabilities")
            if "21" in p:
                report_lines.append("  - FTP open: often allows anonymous login, high risk")
            if "23" in p:
                report_lines.append("  - Telnet open: unencrypted protocol, critical risk")
            if "3306" in p:
                report_lines.append("  - MySQL open: database exposed to network, critical risk")

    report_lines.append("=" * 50)
    report_lines.append("Report generated by SovSwift Security Toolkit v2.0")
    report_lines.append("=" * 50)

    filename = f"sovswift_report_{target}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    with open(filename, "w") as f:
        f.write("\n".join(report_lines))

    print(f"\nReport saved to: {filename}")

target = input("Enter target domain or IP: ")
print("\n--- SovSwift Recon Report v2.0 ---")
run_scan(target)
